### ISSUE TITLE
Nix version pinning

### ISSUE THREAD

**Issue by Radvendii** [nixops4/nixops4#19]
It's not clear to me where, if anywhere the nix version pulled in by `nix-c-raw` is pinned. That seems important, especially given that the nix c bindings are (a) new and (b) unstable, so if someone depends on the wrong version it may break things.

**Comment by roberth** [comment]
> ### where

It comes in through the `nix` flake input, whose package is copied to the `packages` attrset:

https://github.com/nixops4/nixops4/blob/0deaa22111a2e7c7b0c0aa5d0967837e8ca2c89a/flake.nix#L29

and then used in the `nix-cargo-integration` config:

https://github.com/nixops4/nixops4/blob/0deaa22111a2e7c7b0c0aa5d0967837e8ca2c89a/rust/nci.nix#L9


-----
> ### it may break things.

It's pinned in the `flake.lock` file, so it'd only break if someone overrides it, e.g. by declaring `follows` on their `nixops4` flake input.

If it does break, it would tend to just fail to build, as the "instability" refers to API stability, and not really operational, runtime stability.
Furthermore, the evaluator will be isolated to its own process, so that a potential crash in Nix won't take down resource processes, and no data is lost that way.

**Comment by Radvendii** [comment]
Okay. It might be worth documenting this somewhere, but maybe this issue is enough. My first intuition was that it came from the `nix` input, I just couldn't quite track how it got there.
